
name: CursedSands

dependencies:
- base
- containers
- polysemy
- gloss
- gloss-raster
- lens
- comonad
- data-default
- ghc-prim

default-extensions:
- MultiParamTypeClasses
- FunctionalDependencies
- BlockArguments
- RankNTypes
- ScopedTypeVariables
- ImportQualifiedPost
- DerivingStrategies
- FlexibleContexts
- TypeApplications
- AllowAmbiguousTypes
- LambdaCase
- GeneralizedNewtypeDeriving
- TypeOperators
- DataKinds
- KindSignatures
- ViewPatterns
- GADTs
- DuplicateRecordFields

ghc-options: -threaded -O3 -fno-liberate-case -funfolding-use-threshold1000 -funfolding-keeness-factor1000 -optlo-O3

library:
  source-dirs:
  - src

executables:
  CursedSands:
    source-dirs:
    - app

    main: Main.hs

    dependencies:
    - CursedSands
